### ISSUE TITLE
Same color twice in a row

### ISSUE THREAD

**Issue by livibetter** [alexdantas/nFlood#5]
If next color is same as previous one, then it should not be flooded since it will not make a change to the board, also the counter shouldn't count up.

(I will start on this once codebase rework is done.)

**Comment by alexdantas** [comment]
Indeed, forgot to check that!

Since this is such a small change, I think you could do it right away.
As far as I can see, it's a simple matter of storing the previous color on a global
variable (or not, preferably).

Since I'll have to merge my changes anyway, let me be responsible for adapting
those to your contribution.
